site_name: Framework Documentation
nav:
  - Home: index.md
  - Guide:
    - "Installation Guide": Guide\Installation.md
    - Roadmap: Guide\Roadmap.md
    - Contributing:
      - "Documentation Standards": Guide\Contributing\DocumentationStandards.md
  - API:
    - Classes:
      - Queue: API\Classes\Queue.md
      - MessagingService:
        - Packet: API\Classes\MessagingService\Packet.md
        - Package: API\Classes\MessagingService\Packge.md
        - ChannelListener: API\Classes\MessagingService\ChannelListener.md
    - Libraries:
      - DataStoreService: API\Libraries\DataStoreService.md
      - MessagingService: API\Libraries\MessagingService.md
      - Queue: API\Libraries\Queue.md
    - Sides:
      - Server: API\Sides\Server.md
      - Shared: API\Sides\Shared.md
      - Client: API\Sides\Client.md
    - Internal: API\Internal\index.md
theme:
  name: material
  language: en
  palette:
    primary: black
    accent: blue
repo_url: https://github.com/DontRevealMe/Framework
repo_name: Framework
remote_branch: gh-pages
markdown_extensions:
  - admonition
  - codehilite
  - pymdownx.tasklist:
      custom_checkbox: true